import React , {useEffect} from 'react'
import Head from 'next/head'
import Header from './header';
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'

export default function Layouts({children}) {
    useEffect(() => {
        import("bootstrap/dist/js/bootstrap.min.js");
    }, []);
    
  return (
  <>
  <Head>
    <title>Best Deals</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Header/>
  {children}
  {/* 'footer' */}
  </>
  )
}
